diploiTemplateVersion: V1.0
name: diploi-nextjs-template
description: NextJS template for Diploi
defaultName: Tiny App

stages:
  - name: Production
    identifier: production
  - name: Staging
    identifier: staging
  - name: Development
    identifier: development

contexts:
  - name: app
    identifier: app
  - name: redis
    identifier: redisdiploi

parameterGroups:
  - name: MySQL Database
    identifier: mysql
    toggleable: true
    parameters:
      - name: Host
        identifier: DB_HOST
        defaultValue: mysql.example.com
        type: string
      - name: Password
        identifier: DB_PASSWORD
        defaultValue: ''
        type: secret
  - name: Servers
    identifier: SERVER
    parameters:
      - name: Server count
        identifier: SERVER_REPLICAS
        defaultValue: 2
        type: integer
        stages:
          - production

environmentVariables:
  - identifier: PROJECT_TITLE
    defaultValue: ProjectTitleDefaultFromTemplate
    type: string
    contexts: label=app
  - identifier: SOME_OTHER_SETTING
    defaultValue: asdasd
    type: string
    contexts: label=app

repositories:
  - name: web
    identifier: web
    exampleProjectUrl: https://github.com/NemesysLtd/diploi-tiny-template-example #optional

hosts:
  - name: App
    identifier: app
    urlFormat: 'www-[label].[default-domain]'

ssh:
  - usernameFormat: '[label]'
    contexts: label=app
    stages:
      - development
  - usernameFormat: '[label]-[index]'
    contexts: label=app
    stages:
      - production
  - usernameFormat: '[label]-redis'
    contexts: label=redis

logs:
  - identifier: app-log
    name: App Log
    labelSelector: app=app
    command: tail -n 2000 -F /var/log/app.log
  - identifier: pod-log
    name: Pod Log
    labelSelector: app=app
    command: tail -n 2000 -F /var/log/syslog
  - identifier: api-log
    name: API Log
    labelSelector: app=app
    command: tail -n 2000 -F /var/log/api.log
  - identifier: api-error-log
    name: API Error Log
    labelSelector: app=app
    command: tail -n 2000 -F /var/log/api.log | grep Fatal

actions:
  - identifier: server-restart
    name: Restart servers
    labelSelector: app=app
    command: npm run restart
  - identifier: packages-reinstall
    name: Reinstall packages
    labelSelector: app=app
    command: npm run clean
  - identifier: ping
    name: Ping
    labelSelector: app=app
    command: echo "Pong"
  - identifier: log-test-write
    name: Log test write
    labelSelector: app=app
    command: echo $(date) >> /var/log/test.log

images:
  - identifier: app
    repository: web
    dockerfile: Dockerfile
    buildStages:
      - production
      - staging
    stages:
      - development
      - production
      - staging

storage:
  - identifier: app
    stages:
      - development
    sizeMb: 8000

status:
  url: http://app/api/status
