
#
# Example:
# These will be filled in automatically by core (based on diploi-template.yaml)
#

stage: development

enabled: true

images:
  app: registry-docker-registry.registry/myfirstdeploiment/app:latest

hosts:
  app: xxx.diploinetes.nemesys.fi

storage:
  - label: app
    hostPath: /storage/d11111/volume-app
    sizeMB: 8000

parameterGroups:
  mysql:
    enabled: false,
    parameters:
      DB_HOST: mysql,
      DB_DB_PASSWORD: pw

env:
  - name: SMTP_HOST
    value: somehost.someplace.net
    selector: label=app
  - name: SMTP_PASSWORD
    value: xyz
    selector: label=app

sshInternalProxyPublicKey: xxxx

repositories:
  web:
    url: https://github.com/MarcusAhlfors/myservice
    branch: main
    gitUserName: info@diploi.dev
    gitUserEmail: Diploi User
