apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
    - port: {{ ternary 80 8080 .Values.enabled }}
      name: app
  selector:
    app: {{ ternary "app" "disabled" .Values.enabled }}


